apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-picker-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-picker-simple
  template:
    metadata:
      labels:
        app: word-picker-simple
    spec:
      containers:
      - name: world-picker
        image: donamodh/word-picker:v2.1
        ports: 
        - containerPort: 5000
        volumeMounts:
        - name: options-config-map
          mountPath: /code/config
        env:
        - name: OPTIONS_FILE
          value: /code/config/custom_options.txt
      volumes:
      - name: options-config-map
        configMap:
          name: word-picker-options
